#!/usr/bin/env python3
"""Build a self-contained, evidence-labelled Mac journey report."""
import base64, html, json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
def image(path): return 'data:image/png;base64,'+base64.b64encode((ROOT/path).read_bytes()).decode()
def link(path,label): return f'<a href="https://github.com/amiller/apple-attest-p2p/blob/main/{path}">{label}</a>'
rows=[]
events=[]
for line in (ROOT/'data/nft-base-live-20261007/participant.jsonl').read_text().splitlines():
 try: events.append(json.loads(line))
 except json.JSONDecodeError: pass
start=events[0]['t']
for e in events:
 if e['event'] in ['connecting','attesting','enrolled','getting key','key verified','participating','badge preparing','badge claiming','badge claimed']:
  rows.append(f'<tr><td>+{e["t"]-start:.1f}s</td><td>{html.escape(e["event"])}</td></tr>')
report='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>AttestNode — from first open to Fold</title><style>
:root{color-scheme:light;--paper:#f6f3ee;--ink:#292b2a;--muted:#62645e;--red:#a63224;--line:#dcd7cf}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.6 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:52px 32px 72px}h1{font:500 clamp(40px,7vw,74px)/1.05 Georgia,serif;letter-spacing:-2px;margin:18px 0 22px;max-width:850px}h2{font:500 34px/1.2 Georgia,serif;margin:0 0 18px}h3{font-size:21px;margin:0 0 10px}p{margin:10px 0 18px}a{color:#8a281d;text-underline-offset:4px;overflow-wrap:anywhere}a.button{display:inline-block;background:var(--red);color:white;padding:12px 20px;text-decoration:none;border-radius:7px;margin:6px 12px 6px 0}a:focus-visible,summary:focus-visible{outline:3px solid #b9572d;outline-offset:5px}.eyebrow{font-size:12px;font-weight:700;text-transform:uppercase;letter-spacing:2px;color:var(--red)}.lede{font-size:22px;max-width:750px}.note{color:var(--muted);font-size:15px}.tag{display:inline-block;font-size:12px;font-weight:650;padding:4px 9px;border:1px solid var(--line);border-radius:20px;margin-bottom:12px}.verified{background:#e5ebdf}.pending{background:#f3e4ce}.hero,.pair{display:grid;grid-template-columns:1.2fr 1fr;gap:28px;align-items:center}.hero{margin:36px 0 16px}.hero figure{margin:0}.art{width:100%;border-radius:12px}.app{width:100%;background:white;border:1px solid var(--line);border-radius:10px}.caption{font-size:14px;color:var(--muted);margin-top:10px}.panel{background:#fffdf9;border:1px solid var(--line);border-radius:12px;padding:24px}.section{padding-top:48px;margin-top:38px;border-top:1px solid var(--line)}.step{display:grid;grid-template-columns:55px 1fr;gap:15px;margin:25px 0}.number{font:32px Georgia,serif;color:var(--red)}.step p{max-width:800px}.strip{border-left:3px solid var(--red);padding:8px 20px;background:#eee9e1}table{width:100%;border-collapse:collapse;font-size:15px}td,th{text-align:left;padding:9px;border-bottom:1px solid var(--line)}td:first-child{white-space:nowrap}summary{cursor:pointer;font-weight:650;padding:14px 0}pre{background:#eee9e1;padding:16px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:13px}ul,ol{padding-left:23px}li{margin:8px 0}.two{display:grid;grid-template-columns:1fr 1fr;gap:24px}footer{font-size:14px;color:var(--muted);margin-top:48px}@media(max-width:720px){main{padding:30px 20px 50px}.hero,.pair,.two{grid-template-columns:1fr}h1{letter-spacing:-1px}.lede{font-size:20px}.panel{padding:18px}.hero{gap:18px}.section{padding-top:32px;margin-top:30px}}@media print{details>*{display:block}a.button{background:none;color:black;border:1px solid}main{padding:10px}.section{break-inside:avoid}}
</style></head><body><main>
<header><div class="eyebrow">AttestNode · Mac journey / 07 October 2026</div><h1>Open a peer.<br>Receive a Fold.</h1><p class="lede">A Mac joins the research network, verifies a shared testnet key, and claims a participant receipt. Its Fold is a porcelain-and-vermilion sculpture derived from that receipt.</p><a class="button" href="https://github.com/amiller/apple-attest-p2p/releases/tag/v0.1.0-rc.2">Download the Mac app</a> <a href="#journey">Walk through the journey ↓</a><p class="note">Apple silicon · macOS 27 · Full Security · SIP enabled. No wallet, gas, Xcode or developer account required for Level 1.</p></header>
<div class="hero"><figure><img class="app" src="APP_IMAGE" alt="Actual app capture: You’re connected, shared testnet key verified, Participant NFT #1 confirmed, View NFT receipt and Developer upgrade buttons"><figcaption class="caption">Actual RC2 app content capture. Real Apple App Attest and Base Sepolia; seed and participant ran on the same Mac. No desktop or window chrome is included.</figcaption></figure><figure><img class="art" src="FOLD_IMAGE" alt="Gabe’s Fold: spiralling porcelain ribbons around a vermilion interior"><figcaption class="caption">Actual published artwork for Gabe’s #2. This is the NFT image, not a screenshot of artwork displayed inside the app.</figcaption></figure></div>
<div class="strip"><strong>Today’s boundary</strong><p>Automatic joining and receipt claiming work. Fold artwork has been issued separately for the two existing participants. RC2 still opens the original receipt link; in-app artwork and automatic artwork publication for new claims remain to be built.</p></div>
<section class="section" id="journey"><div class="eyebrow">Journey 01 / participant</div><h2>What your friend does</h2>
<div class="step"><div class="number">01</div><div><h3>Download and open</h3><p>Download <strong>AttestNode-macOS27-arm64-v0.1.0-rc.2.zip</strong>, extract it and open <strong>Node.app</strong>. Complete the normal macOS first-open confirmation if shown.</p><span class="tag pending">Clean second-Mac first-open capture pending</span></div></div>
<div class="step"><div class="number">02</div><div><h3>Let the app connect</h3><p>It verifies the running app through Apple App Attest, contacts a peer, receives the shared testnet key and verifies an exchange receipt. You do not choose a network or paste a key.</p><span class="tag verified">Observed · zero app buttons after launch</span></div></div>
<div class="step"><div class="number">03</div><div><h3>See “You’re connected”</h3><p>The app shows <strong>Shared testnet key verified</strong> and <strong>Participant NFT #1 confirmed</strong>, with the personal account address. The recorded first run took approximately <strong>48 seconds</strong>; this is an observation, not a promised wait time.</p><p>Gabe subsequently reported success on a second Mac. His token #2 mint and ownership were checked independently on chain; his complete first-open journey was not recorded.</p></div></div>
<div class="step"><div class="number">04</div><div><h3>See your Fold</h3><p>Existing participants keep the same token number and owner in the main artwork collection. Gabe does not need another claim. The app’s receipt button still points to the earlier receipt; use the link below for the Fold NFT.</p><a href="https://sepolia.basescan.org/token/0xc3da5f4d5013dD6fB4a16EF3ace0C0F9e1F8C1Ed?a=2">Open Gabe’s Fold #2 ↗</a></div></div>
<div class="step"><div class="number">05</div><div><h3>Keep participating—or come back later</h3><p>Closing the window leaves the peer running. Quit stops it. In the recorded packaged-app restart, the same account and token #1 returned without a second mint. Keep the app’s saved identity and Keychain entries.</p><span class="tag verified">Restart verified by log and chain read</span></div></div></section>
<section class="section"><div class="eyebrow">Journey 02 / independent builder</div><h2>Make it your own signed app</h2><span class="tag pending">Implemented flow · real second-team acceptance pending</span><p>Level 2 recognizes a build signed by an independent Apple Developer team. It is more than entering a Team ID: you need signing authorization, a certificate and a matching profile. Apple credentials stay in your own Xcode, Keychain or protected CI environment.</p><ol><li>In the original app, choose <strong>Developer upgrade… → Save invitation…</strong>.</li><li>Build the pinned release without changing executable code. Use the invitation’s account-specific bundle ID and your own team to sign and notarize it.</li><li>Register the signed copy using the documented helper, then open it and import the invitation.</li><li>Bring its upgrade request back to the original app, compare the key fingerprint and approve the handoff.</li><li>Return to your signed copy. The intended result is a builder NFT linked to your participant receipt at the original account.</li></ol><p>There is no verified builder-success screenshot yet. This is the implemented journey to test, not a completed friend run.</p>BUILDER_LINK</section>
<section class="section"><div class="eyebrow">Friction / preserve the evidence</div><h2>One useful report, not a terminal gauntlet</h2><div class="two"><div class="panel"><h3>What RC2 supports</h3><p>If “Verifying this app” keeps repeating, open <strong>Show technical details</strong> and use <strong>Save status image…</strong> in the Testnet menu. Send that image and visible error text to the person coordinating the test, then choose <strong>Quit peer</strong> to stop repeated attempts.</p><p class="note">SIP being enabled does not establish Full Security. An Apple error code alone does not establish the cause. Do not delete identity state as a generic reset.</p></div><div class="panel"><h3>Product requirement</h3><p>Explain supported security settings before a failed enrollment, distinguish permanent errors from temporary outages, and offer a single shareable diagnostic report. This clearer Mac failure experience is still work to do.</p><p class="note">Gabe’s run exposed security-mode and stale-enrollment friction. His eventual success does not make that first experience frictionless.</p></div></div></section>
<section class="section"><div class="eyebrow">Agent transcript / actual recorded events</div><h2>From launch to receipt</h2><p>This is a readable extraction of the real application log, not a simulated animation or a newly executed run. Signing Mac: notarized RC2 payload; Gatekeeper was disabled on that machine.</p><div class="pair"><table><thead><tr><th>After launch</th><th>Logged event</th></tr></thead><tbody>EVENT_ROWS</tbody></table><div><h3>What the agent checked</h3><p>Opened the app through LaunchServices; independently checked the mint transaction and account ownership; reopened the extracted release ZIP; confirmed token #1 returned and the receipt counter did not advance.</p><p>The main Fold collection was then deployed separately. Both existing token owners and metadata were verified at block <strong>47826297</strong>, and its deployed runtime matched the compiled contract.</p>TRANSCRIPT_LINK · LOG_LINK · VERIFY_LINK</div></div><details><summary>Exact launch command and evidence boundaries</summary><pre>open -n --stdout build/participant.jsonl --stderr build/participant.err \
  build/developer-id/notarized/Node.app --args \
  --capture-status "$PWD/build/participant-claimed.png"</pre><p>The launch argument only selected a capture location. The shared-key receipt and participant claim used real services. Both processes ran on the signing Mac. The restart log is valid; its saved image is unusable and is deliberately omitted. No friend chat screenshots or signing secrets are included.</p></details></section>
<section class="section"><div class="eyebrow">PRD / completion criteria</div><h2>What makes this ready to hand off</h2><table><thead><tr><th>Outcome</th><th>Evidence today / remaining work</th></tr></thead><tbody><tr><td>Open → join → claim</td><td>Recorded operator run; Gabe’s successful receipt verified. Clean first-open friend capture still needed.</td></tr><tr><td>Return without duplication</td><td>Packaged restart verified on signing Mac; friend restart capture pending.</td></tr><tr><td>Receive a polished Fold</td><td>Two existing NFTs published. New-claim artwork automation and app integration pending.</td></tr><tr><td>Earn Level 2</td><td>Policy and handoff implemented; independent-team signing and successful claim still need a real run.</td></tr><tr><td>Understand a failure</td><td>Status image and details available; clearer preflight and terminal-error UX pending.</td></tr></tbody></table><p>PRD_LINK · AUDIT_LINK · FRIEND_LINK</p><p class="note">These are research testnet receipts, not permanent unique-device or unique-person identities. The NFT account key is distinct from the shared testnet key. Fold’s geometry derives from public receipt identity; the publisher currently controls artwork updates until frozen.</p></section>
<footer>Revision: 7 October 2026 · Mac RC2 observed evidence + main Fold collection publication.<br>Anyone holding this unlisted report link can view and download it. The HTML embeds its images and remains readable offline; source and explorer links need internet access. iPhone/TestFlight is a separate acceptance track.</footer>
</main></body></html>'''
replacements={'APP_IMAGE':image('data/nft-base-live-20261007/participant-claimed.png'),'FOLD_IMAGE':image('artwork/fold/gabe-token-2.png'),'EVENT_ROWS':''.join(rows),'BUILDER_LINK':link('release/builder-guide.md','Open the step-by-step builder guide ↗'),'TRANSCRIPT_LINK':link('release/agent-transcript-nft-base.md','Full transcript'),'LOG_LINK':link('data/nft-base-live-20261007/participant.jsonl','Raw events'),'VERIFY_LINK':link('release/main-collection-deployment.json','Collection verification'),'PRD_LINK':link('release/PRD.md','Full PRD'),'AUDIT_LINK':link('release/acceptance-audit.md','Acceptance audit'),'FRIEND_LINK':link('release/friend-guide.md','Friend instructions')}
for key,value in replacements.items(): report=report.replace(key,value)
out=ROOT/'build/mac-journey-fold.html';out.parent.mkdir(exist_ok=True);out.write_text(report);print(out)
