#!/usr/bin/env python3
"""Build the self-contained RC2 friend handoff from verified local release assets."""
import base64,html,json,hashlib,re
from pathlib import Path
r=Path(__file__).resolve().parents[2]
def data(path,mime):return 'data:'+mime+';base64,'+base64.b64encode((r/path).read_bytes()).decode()
app='build/rc2/AttestNode-macOS27-arm64-v0.1.0-rc.2.zip';assert hashlib.sha256((r/app).read_bytes()).hexdigest()=='145cd977390c0c01be006c2a056a1890449cbf26c7e6d0a24820f11de1ad3b25'
events=[json.loads(l) for l in (r/'data/nft-base-live-20261007/participant.jsonl').read_text().splitlines() if l.startswith('{')];start=events[0]['t'];names={'connecting':'Connecting','attesting':'Verifying this app','getting key':'Getting the shared key','key verified':'Shared key verified','badge preparing':'Creating personal NFT account','badge claiming':'Claiming NFT','badge claimed':'Participant NFT #1 confirmed'}
rows=''.join(f'<tr><td>{e["t"]-start:.1f}s</td><td>{names[e["event"]]}</td></tr>' for e in events if e['event'] in names)
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>AttestNode — join the testnet</title><style>
*{box-sizing:border-box}body{margin:0;background:#f2f5f1;color:#172c23;font:17px/1.55 system-ui,sans-serif}main{max-width:1000px;margin:auto;padding:42px 24px 72px}h1{font-size:clamp(32px,6vw,54px);line-height:1.1;margin:10px 0 20px}h2{font-size:25px;margin-top:36px}p{max-width:75ch}.label{font-size:14px;letter-spacing:.07em;text-transform:uppercase}.button{display:inline-block;background:#164f39;color:white;text-decoration:none;border-radius:9px;padding:14px 20px;font-weight:650;margin:10px 0}.card,figure,details{background:white;padding:22px;border:1px solid #d8e2d9;border-radius:12px;margin:22px 0}figure img{width:100%;height:auto;display:block}figcaption,.small{font-size:14px;color:#4a5e52}a{color:#18573d;overflow-wrap:anywhere}pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.5 ui-monospace,monospace}table{width:100%;border-collapse:collapse}td{padding:8px;border-bottom:1px solid #dde4dd}td:first-child{width:90px}summary{cursor:pointer;font-weight:650}.grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.grid .card{margin:0}code{overflow-wrap:anywhere}@media(max-width:650px){main{padding:28px 16px}.grid{grid-template-columns:1fr}figure{padding:8px}figcaption{padding:10px}}
</style></head><body><main>
<div class="label">Research testnet · Mac prerelease RC2</div><h1>Open the app.<br>Join the network.<br>Receive your NFT.</h1>
<p>AttestNode verifies its Apple signing identity, receives a shared testnet key from a peer, and automatically claims a participant NFT for your personal app account. No wallet, gas purchase, or developer account is needed for this first step.</p>
<a class="button" download="AttestNode-macOS27-arm64-v0.1.0-rc.2.zip" href="APP_DATA">Download the Mac app</a>
<p class="small">Apple Silicon · macOS 27 · 192 KB ZIP · Developer ID signed and notarized</p>
<div class="card"><strong>Try it in three steps</strong><ol><li>Download and extract the ZIP.</li><li>Open <strong>Node.app</strong> and complete macOS’s normal first-open confirmation if shown.</li><li>Wait for <strong>You’re connected</strong> and <strong>Participant NFT confirmed</strong>. The recorded run took 48 seconds; network delays may take longer.</li></ol><p>Choose <strong>View NFT receipt</strong> to inspect your souvenir. Closing the window keeps your peer running; Quit stops it. Reopening restores the same NFT.</p></div>
<figure><img src="SCREEN_DATA" alt="Actual Mac app showing You're connected, shared testnet key verified, and Participant NFT 1 confirmed"><figcaption>Real AppKit capture from the notarized app on Base Sepolia. The app confirmed NFT #1 without an application button press. This capture shows app content, excluding desktop and window chrome.</figcaption></figure>
<div class="grid"><section class="card"><h2>Level 1 · participant</h2><p><strong>Observed:</strong> real Apple attestation, peer key exchange, automatic NFT mint, and recovery of the same NFT after reopening the packaged ZIP.</p><p>The seed and participant ran on the same Mac. A clean friend’s Mac with Gatekeeper enabled still needs to be tested.</p></section><section class="card"><h2>Level 2 · independent builder</h2><p>Use <strong>Developer upgrade…</strong> to save an invitation. Build the same app with your own Apple Developer team and the invitation’s account-specific bundle ID. Approve the handoff from the original app to earn the next NFT.</p><p><strong>Preview:</strong> this flow is implemented, but its first real second-team acceptance run is pending. Source access and a paid independent developer team are required.</p></section></div>
<h2>What the agent observed</h2><p>These times come from the actual app’s event log. No service mocks or simulated Apple assertions were used.</p><table><thead><tr><th align="left">Since launch</th><th align="left">Observed event</th></tr></thead><tbody>EVENT_ROWS</tbody></table>
<p>The agent independently verified that NFT #1 belongs to the participant-controlled account, not the relay sponsor. After reopening the release ZIP, the same NFT returned and the contract still had only one minted token.</p>
<p><a href="https://sepolia.basescan.org/tx/0x111c7b5e723dc290df0694c6bcc34c6cf4f1c8b04b321fee52391a08c4b56037">Inspect the confirmed mint transaction</a></p>
<details><summary>Read the agent transcript and verification limits</summary><pre>TRANSCRIPT</pre><a download="participant.jsonl" href="LOG_DATA">Download the observed event log</a></details>
<details><summary>Level 2 setup and account handoff guide</summary><pre>BUILDER</pre></details>
<details><summary>Product requirements and remaining acceptance tests</summary><pre>PRD</pre></details>
<details><summary>Check the app download and build provenance</summary><p>Unsigned app bytes matched independent GitHub CI and clean Mac builds. Apple signatures and the stapled notarization ticket were checked separately. The build Mac has Gatekeeper disabled, so this does not establish clean-Mac first-open behavior.</p><pre>MANIFEST</pre><p><a href="https://github.com/amiller/apple-attest-p2p/releases/tag/v0.1.0-rc.2">GitHub release and source (repository access required)</a></p></details>
<h2>What these receipts mean</h2><p>They are research testnet souvenirs with no monetary value. The shared key proves network participation. Your NFT account uses a separate device-only Keychain key. Losing that key before a successful handoff loses account control; the sponsor cannot recover it.</p><p>App Attest does not expose a permanent Mac-owner ID. Level 1 limits claims per admitted app key; Level 2 allows one claim per verified independent developer team and one upgrade per participant NFT. A team can represent multiple people.</p>
<p class="small">Anyone holding this unlisted link can view it and download the app. It is not account-authenticated. The private source repository remains private. Screenshot and transcript reflect the recorded run, not a completed second-Mac or second-team test.</p>
</main></body></html>'''
values={'APP_DATA':data(app,'application/zip'),'SCREEN_DATA':data('data/nft-base-live-20261007/participant-claimed.png','image/png'),'EVENT_ROWS':rows,'TRANSCRIPT':html.escape((r/'release/agent-transcript-nft-base.md').read_text()),'BUILDER':html.escape((r/'release/builder-guide.md').read_text()),'PRD':html.escape((r/'release/PRD.md').read_text()),'MANIFEST':html.escape((r/'release/v0.1.0-rc.2.json').read_text()),'LOG_DATA':data('data/nft-base-live-20261007/participant.jsonl','application/x-ndjson')}
page=re.sub('|'.join(values),lambda m:values[m.group()],page)
(r/'build/rc2/friend-handoff.html').write_text(page)
print('Reviewed-input handoff HTML written:',len(page),'bytes')
