#!/usr/bin/env python3
"""Render the proposed Mac journey as a self-contained interactive storyboard."""
from pathlib import Path
import base64,json
ROOT=Path(__file__).resolve().parents[2]
HERE=Path(__file__).resolve().parent
slides=[]
def add(chapter,title,action,result,next_,surface,content,status='Proposed interface · illustrative state'):
 slides.append(dict(sequence=f"{len(slides)+1:02}",chapter=chapter,title=title,action=action,result=result,next=next_,surface=surface,content=content,status=status))
def button(label,target=None,secondary=False):
 return f'<button class="{"secondary" if secondary else "primary"}" data-{("go="+str(target)) if target is not None else "advance"}>{label}</button>'
def small(text):return f'<p class="quiet">{text}</p>'
def art(kind=''):
 return f'<div class="art {kind}" role="img" aria-label="Porcelain Fold sculpture with vermilion interior"><span class="assembly-stamp" aria-hidden="true">002</span><span class="assembly-material" aria-hidden="true">PORCELAIN / VERMILION</span></div>'
def split(left,right):return '<div class="split assembly-split"><div class="visual">'+left+'</div><div class="copy">'+right+'</div></div>'
def steps(rows):
 return '<div class="checklist">'+''.join(f'<div><span class="{s}">{"✓" if s=="done" else "◌" if s=="current" else "○"}</span><p>{a}<small>{b}</small></p></div>' for s,a,b in rows)+'</div>'
def field(label,value):return f'<div class="field"><span>{label}</span><strong>{value}</strong></div>'
add('Join','A friend sends you the app','Choose Download for Mac.','The page makes the Mac and security requirements visible before installation.','Extract the ZIP and open Node.app.','browser',split(art(),'<div class="kicker">ATTESTNODE / MAC</div><h2>Join the<br>network.</h2><p>One app. A peer connection.<br>A Fold of your own.</p>'+button('Download for Mac ↓')+'<div class="requirements">Apple silicon · macOS 27<br>Full Security · System Integrity Protection on</div><p class="quiet">No wallet, payment or developer account needed.</p>'))
add('Join','Open the downloaded app','Extract the ZIP, then open Node.app.','macOS may ask you to confirm opening an app downloaded from the internet.','Choose Open to launch. This is an OS handoff, not an enrollment form.','desktop','<div class="finder"><div class="finderbar">Downloads</div><div class="files"><div><span class="fileicon">ZIP</span>AttestNode…zip</div><div class="selected"><span class="appicon">A</span>Node.app</div></div></div><div class="sheet os"><div class="appicon">A</div><h3>Open “Node”?</h3><p>This app was downloaded from the internet.</p><p class="quiet">Illustrative macOS confirmation. Exact wording and whether it appears depend on the Mac.</p><div class="actions">'+button('Cancel',0,True)+button('Open')+'</div></div>', 'OS handoff reconstruction · not a captured system dialog')
add('Join','The app checks itself','Nothing to press. The storyboard’s Next button advances time.','The first status tells you what is happening without exposing keys or contract addresses.','Once Apple verifies the app, it finds a peer.','app',split('<div class="seal"><span>✳</span></div><span class="visual-caption">01 / VERIFY</span>','<div class="kicker">GETTING STARTED</div><h2>First, verify<br>the app.</h2><p>Verifying this copy of AttestNode with Apple.</p>'+steps([('current','Verify this app','Apple App Attest'),('waiting','Connect to a peer','Find the research network'),('waiting','Receive your Fold','Claim your participant receipt')])+small('This happens automatically. Keep the app open.')))
add('Join','Connect to a peer','Keep the app open. No seed phrase or faucet form.','The app explains that it is receiving and checking the shared testnet key.','A verified exchange lets it claim your participant receipt.','app',split('<div class="peers"><div class="peer">Your Mac</div><div class="connection"><i></i><i></i><i></i></div><div class="peer other">A peer</div></div><span class="visual-caption">02 / CONNECT</span>','<div class="kicker">JOINING THE NETWORK</div><h2>Peer found.<br>Key incoming.</h2><p>Receiving the shared testnet key and checking the exchange receipt.</p>'+steps([('done','App verified','This build is admitted'),('current','Key exchange','Checking the peer’s receipt'),('waiting','Participant receipt','Your personal account is next')])+small('Your personal NFT key stays separate from the shared network key.')))
add('Join','Your receipt becomes your Fold','Wait while the personal receipt is claimed and its artwork is prepared.','Joining, claiming and artwork preparation are separate visible steps. A slow render must not look like a failed network connection.','Reveal the Fold when its image and receipt are ready.','app',split(art('preparing')+'<div class="art-label">03 / PREPARE YOUR FOLD</div>','<div class="status"><i></i> Connected</div><h2>You’re in.<br>Fold next.</h2><p>Your receipt is confirmed. Its Fold is being rendered from the public receipt number.</p>'+steps([('done','Network joined','Shared key verified'),('done','Participant receipt claimed','Saved to your personal account'),('current','Artwork being prepared','You can keep participating while this finishes')])+small('Your receipt is saved. It will be here when you return.')),'Proposed interface · artwork automation not yet implemented')
add('Join','Your Fold arrives','See your Fold. Choose View your NFT, or leave the app participating.','The sculpture leads; the verified network status is quiet but unambiguous.','Return any time. The optional next step is becoming an independent builder.','app',split(art()+'<div class="art-label">RECEIPT 002 / PARTICIPANT</div>','<div class="status"><i></i> You’re part of the network</div><h2>Your Fold.<br><span class="edition-number">002</span></h2><p>Your receipt, made tangible. Keep the app running to participate in the network.</p><div class="tokenline"><strong>Participant #2</strong><span>Receipt verified</span></div>'+button('View your NFT')+'<div class="nextchapter"><h4>Next: build independently.</h4><p>Sign the app with your Apple Developer team to earn the independent-builder receipt.</p>'+button('Become an independent builder →',8,True)+'</div>'+small('Closing the window keeps your peer running. Quit stops it.')),'Proposed interface · uses Gabe’s real published Fold #2')
add('Join','Inspect the receipt without losing the story','Choose View your NFT.','A proposed receipt view opens with the image, ownership and two distinct links: the artwork NFT and its underlying attestation receipt.','Return to the app; the peer has kept running.','browser',split(art(),'<div class="kicker">YOUR RESEARCH RECEIPT</div><h2>Fold / 002</h2><p>Porcelain and vermilion.<br>Derived from this participant’s public receipt.</p>'+field('Level','Participant')+field('Owner','Your personal account · 0x6e25…480b')+field('Network','Base Sepolia · research testnet')+'<div class="actions"><a class="primary" href="https://sepolia.basescan.org/token/0xc3da5f4d5013dD6fB4a16EF3ace0C0F9e1F8C1Ed?a=2" target="_blank" rel="noopener">Open actual NFT ↗</a><a class="secondary" href="https://sepolia.basescan.org/token/0x6Ac5fb83f5BF615842b5A9a6C50b8011FaB50c3B?a=2" target="_blank" rel="noopener">Original receipt ↗</a></div>'+small('No monetary value. This receipt does not identify a unique person or physical Mac.')),'Proposed receipt page · image and NFT link are real')
add('Return','Come back to the same Fold','Quit, then reopen the app.','The app restores the same personal account and receipt. It reconnects without creating a second claim.','Keep participating or start the builder journey.','app',split(art(),'<div class="status"><i></i> Connected again</div><h2>Welcome back.</h2><p>Reconnected. Your account and Fold are unchanged.</p><div class="tokenline"><strong>Participant #2</strong><span>Existing receipt restored</span></div>'+button('Become an independent builder →',8)+small('Same account. Same Fold. No second claim.')+'<div class="nextchapter"><h4>Back in the network.</h4><p>Keep it open to participate. You can close this window.</p></div>'),'Proposed interface · restart behavior verified for operator token #1, not Gabe’s #2')
add('Build','Understand what the next level asks','Choose Become an independent builder.','Before any handoff, the app explains the cost and work: use an independent paid Apple Developer team and sign an unchanged copy.','Save an invitation that links the new copy to your existing account.','app','<div class="builder-intro"><div class="kicker">INDEPENDENT BUILDER / LEVEL 2</div><h2>Same code.<br>Your signature.</h2><p>Show that the network accepts an independently signed copy of the app.</p><div class="three"><div><span>01</span><h4>Keep your Fold</h4><p>Both receipts stay at your existing account.</p></div><div><span>02</span><h4>Bring your team</h4><p>You need an Apple Developer team different from the publisher.</p></div><div><span>03</span><h4>Approve the move</h4><p>Your original app authorizes the new copy.</p></div></div>'+button('Save invitation…')+small('Keep the original app and its Keychain until the handoff is confirmed.')+'</div>')
add('Build','Save the link to your account','Save invitation.json from the original app.','The save panel exports public account information. It contains no private key and cannot transfer ownership by itself.','Open the build guide with the invitation alongside it.','app','<div class="underlay"><div class="kicker">INDEPENDENT BUILDER</div><h2>Keep your<br>account.</h2></div><div class="sheet"><h3>Save your invitation</h3>'+field('Save as','invitation.json')+field('Where','Downloads')+'<p>This file links your independently signed copy to your participant account.</p><p class="quiet">Contains public information only. Keep the original app installed.</p><div class="actions">'+button('Back',8,True)+button('Save invitation')+'</div></div>','Proposed interface · save-panel reconstruction')
add('Build','Set up your own signing identity','Fork the release and configure its invitation-specific App ID under your team.','The browser guide walks through the Apple Developer portal and Xcode handoff instead of treating a Team ID as a credential.','Build the unchanged pinned source; sign and notarize it with Developer ID.','browser','<div class="guide"><div class="kicker">BUILD GUIDE / YOUR APPLE DEVELOPER TEAM</div><h2>Build it.<br>Sign it.</h2><div class="two"><div>'+steps([('current','Fork and pin the release','Check out v0.1.0-rc.2'),('waiting','Apple Developer portal','Create the exact App ID from invitation.json and a matching profile'),('waiting','Xcode / Keychain','Use your team’s Developer ID signing identity')])+'</div><div class="guidecard"><h4>Keep these local</h4><p>Apple sign-in, certificate private keys and signing passwords stay in your tools.</p><p>The app never asks you to paste them.</p><p class="quiet">Use the invitation’s bundle ID. Do not change executable source to personalize the app.</p></div></div>'+button('Show the build & registration step')+'</div>','Proposed guide screen · Apple portal/Xcode steps still require real setup')
add('Build','Build, sign and register','Use the pinned build/signing instructions, then register that exact signed app.','This step explicitly leaves the app for Xcode and the command line. It is not presented as a one-click setup.','Open the independently signed copy and import your invitation.','terminal','<div class="terminalhead">Build workspace · illustrative output, not an executed session</div><pre><span class="dim"># Build unchanged release source with invitation bundle ID</span>\npython3 scripts/release/build_mac.py --gui \\\n  --out build/my-unsigned --bundle-id "$APPLE_BUNDLE_ID"\n\n<span class="dim"># Sign and notarize via the build guide’s Xcode/CI steps.</span>\n<span class="dim"># Then register the exact signed application:</span>\npython3 scripts/release/register_mac_build.py \\\n  --app /path/to/AttestNode.app \\\n  --relay https://pod.dstack.soc1024.com/apple-attest-p2p-relay/nft\n\n<span class="success">Expected: admitted code registered</span>\n<span class="dim">Opening the app must still produce valid Apple attestation.</span></pre><div class="terminalbottom">'+button('Open your signed copy')+'<span>Guide handoff · no commands execute in this prototype</span></div>','Concept handoff · expected output, not a successful second-team build')
add('Build','The new copy requests the handoff','In your signed copy, import invitation.json and save the upgrade request.','The new copy checks its signing team and account binding. It presents a key fingerprint to compare on both apps.','Take the request back to the original app.','app','<div class="builder-intro"><div class="kicker">YOUR SIGNED COPY</div><h2>New copy.<br>Same account.</h2><p>Import the invitation saved by your original app.</p>'+field('Selected file','invitation.json')+field('Target account','Your original participant account')+field('New key fingerprint · illustrative','C7B2 · 91AD · 6F08 · E432')+'<div class="callout">Your original app must approve this request. Importing the invitation does not move control.</div>'+button('Save upgrade request…')+small('The app must verify your independent team and live attestation before creating this request.')+'</div>')
add('Build','The original app asks for consent','Import the request in the original app. Compare the fingerprint with your signed copy, then approve.','The confirmation makes the account-control change explicit before signing it.','Wait for the confirmed handoff, then return to your signed copy.','app','<div class="underlay"><div class="kicker">ORIGINAL APP</div><h2>Review.<br>Then approve.</h2></div><div class="sheet"><div class="kicker">REVIEW HANDOFF</div><h3>Let your signed copy<br>control this account?</h3>'+field('Account','Your participant account · Fold #2')+field('New key fingerprint · illustrative','C7B2 · 91AD · 6F08 · E432')+'<p>Compare this fingerprint with the one in your signed copy. After confirmation, this original copy can no longer control the account.</p><div class="actions">'+button('Cancel',12,True)+button('Approve handoff')+'</div><p class="quiet">Only approve the request you created. Expired requests must be recreated.</p></div>')
add('Build','The account moves; the Fold stays','Return to your signed copy after confirmation.','The new copy controls the original account and claims the independent-builder receipt. Both receipts stay linked there.','Keep this signed copy and its Keychain safe.','app',split(art()+'<div class="art-label">EXISTING PARTICIPANT FOLD · ART STUDY</div>','<div class="status"><i></i> Handoff confirmed</div><h2>You built it.<br>You signed it.</h2><p>Your signed copy now controls your original account.</p><div class="tokenline"><strong>Participant receipt</strong><span>Preserved</span></div><div class="tokenline"><strong>Independent builder</strong><span>Level 2 · expected receipt</span></div>'+button('Return to your collection',5)+small('Keep this signed copy and its Keychain safe. Both receipts belong to your original account.')),'Future success-state mockup · independent-team acceptance unverified')
add('Help','An Apple verification error has a useful screen','Read the failure state instead of watching endless retries.','The app distinguishes failure from progress and offers one report to share. It does not diagnose security mode from a generic Apple error alone.','Check the supported settings or share diagnostics; preserve the app identity.','app','<div class="builder-intro"><div class="kicker">APPLE VERIFICATION DID NOT COMPLETE</div><h2>Verification<br>paused.</h2><p>Your saved identity is still here. Repeated attempts have been paused.</p><div class="callout"><h4>Check the requirements</h4><p>This demo requires Apple silicon, macOS 27, Full Security and SIP enabled. SIP alone does not establish Full Security.</p><p class="quiet">We have not established the cause of this failure.</p></div><div class="actions">'+button('Share diagnostic report')+button('Try again',2,True)+'</div>'+small('Your account and receipt have not been reset.')+'</div>','Proposed error UX · not implemented in RC2')
add('Help','One report your friend can send','Review the diagnostic report before sharing it.','The report shows app/OS version, the failed stage and error information. It excludes private keys and signing credentials.','Send it to the coordinator. No repeated terminal-command requests.','app','<div class="builder-intro"><div class="kicker">REVIEW BEFORE SHARING</div><h2>One report.<br>Useful details.</h2>'+field('App / system','AttestNode RC2 · macOS 27 · Apple silicon')+field('Failed stage','Apple App Attest verification')+field('Startup security policy','Not determined — do not infer from SIP')+field('Saved identity','Preserved')+'<div class="callout">The exported report would include the exact error chain and recent relevant events. Review those details before sending.</div><div class="actions">'+button('Save report…',15)+button('Back to app',5,True)+'</div>'+small('Review the full report before sending it. It contains no private keys.')+'</div>','Proposed report review · illustrative fields, no diagnostics collected')
encoded=base64.b64encode((ROOT/'artwork/fold/gabe-token-2.png').read_bytes()).decode()
actual=base64.b64encode((ROOT/'data/nft-base-live-20261007/participant-claimed.png').read_bytes()).decode()
template=(HERE/'template.html').read_text().replace('__ART__',encoded).replace('__ACTUAL__',actual).replace('__SLIDES__',json.dumps(slides).replace('</','<\\/'))
out=ROOT/'build/mac-visual-journey.html';out.parent.mkdir(exist_ok=True);out.write_text(template)
(ROOT/'build/mac-visual-journey-scenes.json').write_text(json.dumps(slides,indent=2)+'\n')
print(f'{out}: {len(slides)} screens')
